### ISSUE TITLE
Arduino 1.6.8 compilation error

### ISSUE THREAD

**Issue by reaper7** [koen-github/PushBullet-ESP8266#2]
with error:
PushBullet.cpp:87:87: error: default argument given for parameter 2 of 'void PushBullet::registerThisDevice(String, String)'

so...simply replace line 87 from:

```
void PushBullet::registerThisDevice(const String nickName, const String pushToken = "")
```

to

```
void PushBullet::registerThisDevice(const String nickName, const String pushToken)
```

solve problem

**Comment by koen-github** [comment]
Thank you for letting me know, I was busy developing a way to register the arduino as a device in pushbullet. So it would be possible to send push messages to the esp8266.
But next time I will implement a new feature in another branch ;)

**Comment by reaper7** [comment]
good news :) 
release date? ;)

BTW. something changed on pushbullet?
because esp sending eg note but nothing reaches on other devices...

**Comment by koen-github** [comment]
I wanted to create something so I could push messages to the esp8266 connected to a Nokia 5510 LCD. To retrieve the push messages from pushbullet I need to use a json library, but it uses too much memory so I did not get that working yet (actually I only want to strip out the message so nothing else, do have an idea to do something like that without using a full json library?).

It happens sometimes that push notifications are not delivered, could you post your debug log here? Of course without your api key (so the sended response and reply).

**Comment by reaper7** [comment]
maybe other json libs?
https://github.com/squix78/json-streaming-parser
https://github.com/nomadnt/uJSON
maybe from other examples:
https://github.com/Yigihu/Simple-Arduino-JSON-Client

---
my debug do NOT show that "FAILED TO SEND"
```
n
Pushbullet note pushing
Request string: 
POST/v2/pushes HTTP/1.1
Host: api.pushbullet.com
User-Agent: ESP8266/NodeMCU 0.9
Accept: */*
Content-Type: application/json
Content-Length: 57
Access-Token: xxxxxxx

{"body":"Hello, from me","title":"Message","type":"note"}
```

**Comment by koen-github** [comment]
Did you also try it with the latest version in master branch?

**Comment by reaper7** [comment]
Yes, today, the same :(
but I remember that before (month or more), everything worked properly.
I'm using arduino IDE 1.6.8 and latest github version of arduino/esp8266

**Comment by koen-github** [comment]
Hmm, then I think something changed in the PushBullet API, will try it soon

**Comment by reaper7** [comment]
maybe, but works for You?

**Comment by koen-github** [comment]
It did some time ago, but I didn't tested the API the last three weeks.

**Comment by reaper7** [comment]
I also check develop version, do not send note or other but register device (opt 'a' from example)

**Comment by reaper7** [comment]
hmm...strange, I reinstall android pushbullet app and register it and now it's working...
but earlier (before reinstall) I received all messages and sms from android to eg firefox ...
